name: Nightly Release

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Install libpcap-devel (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Build
        env:
          GOOS: ${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'macos-latest' && 'darwin' || 'windows' }}
          CGO_ENABLED: ${{ matrix.os != 'macos-latest' }}
        run: |
          mkdir -p dist
          go build -ldflags "-s -w" -o dist/go-ytds_${{ matrix.os }} ./main.go

      - name: Archive binaries
        if: always()
        run: |
          mkdir -p dist/archives
          tar -czvf dist/archives/go-ytds_${{ matrix.os }}.tar.gz -C dist go-ytds_${{ matrix.os }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-ytds_${{ matrix.os }}
          path: dist/archives/go-ytds_${{ matrix.os }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/archives

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="nightly-$(date +'%Y%m%d%H%M%S')"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
